name: MyFirstAction
on: workflow_dispatch
jobs: 
  MyFirstJob:
   runs-on: ubuntu-latest
   steps:
      - name: clone repo
        run: |
          echo "Clone the command"
          echo "Clone the command 2"
